# .github/workflows/pages.yml
name: Deploy slides to GitHub Pages
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # build step would go here if you have one
      - uses: actions/upload-pages-artifact@v3
        with:
          path: slides     # publish this folder
      - id: deployment
        uses: actions/deploy-pages@v4